id: I6DE51D69
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:26:22.108258'
last_modified: '2022-06-18T20:26:22.108270'
parser: null
source_metadata:
  title: rJe btsun Kun dga grol mchogs (1507–1565/1566) Outer, Inner and Secret Biography
  author: རྗེ་བཙུན་ཀུན་དགའ་གྲོལ་མཆོག
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-06-16);
    revision in process, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Volker Caumanns (vc)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:Volker Caumanns (vc)
  text_witnesses: https://sakyaresearch.org/sources/539
  bases:
    019b:
      title: rJe btsun Kun dga grol mchogs (1507–1565/1566) Outer, Inner and Secret
        Biography
      order: 1
      base_file: 019b.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
